const translations = {
  en: {
    nav_home: "Home",
    nav_about: "About Us",
    nav_products: "Products & Services",
    nav_contact: "Contact Us",
    hero_headline: "Global Sourcing & Strategic Trading Solutions",
    hero_subhead: "Import, Export, and Domestic Industrial Solutions. Connecting businesses with high-quality global supply chains.",
    hero_cta: "Explore Our Solutions",
    about_title: "About OCTO NOTO",
    about_desc: "A premier Thai-based trading house specializing in technical sourcing, quality control, and international supply chain management. We act as a strategic partner to ensure our clients get the right product for their specific application.",
    val_1_title: "Technical Sourcing",
    val_1_desc: "Consultation to find the exact match.",
    val_2_title: "Quality First",
    val_2_desc: "Rigorous supplier vetting and quality control.",
    val_3_title: "Strategic Partner",
    val_3_desc: "Long-term value, reliability, and transparent pricing.",
    prod_title: "Products & Services",
    prod_1: "Anti-Rust Packaging (VCI) & ESD Materials",
    prod_2: "Packing Materials & Cartons",
    prod_3: "Industrial O-Rings, Gaskets, & Seals",
    prod_4: "Wire Harnesses, Power Cords, & EV Chargers",
    prod_5: "Industrial & Lab Chemicals",
    prod_7: "Motor & Drive",
    prod_group_industrial: "Industrial Solutions",
    prod_group_inhouse: "Inhouse Brands",
    inhouse_prod_1: "The White Ivory (Coming Soon)",
    catalogue_title: "Download Catalogue",
    catalogue_desc: "Scan the QR code or click the button below to view our full product catalogue.",
    catalogue_btn: "Download via Google Drive",
    contact_title: "Contact Us",
    contact_company: "OCTO NOTO CO., LTD.",
    contact_address: "88/206 Grande Pleno Suksawat-Rama 3, Pracha Uthit 54, Thung Khru District, Bangkok 10140, Thailand",
    footer_copy: "© 2026 OCTO NOTO CO., LTD. All Rights Reserved.",
    form_name_label: "Full Name",
    form_name_placeholder: "John Doe",
    form_company_label: "Company Name",
    form_company_placeholder: "Your Company Ltd.",
    form_email_label: "Email Address",
    form_email_placeholder: "john@example.com",
    form_phone_label: "Phone Number",
    form_phone_placeholder: "+1 234 567 8900",
    form_subject_label: "Subject",
    form_subject_placeholder: "Inquiry about VCI Packaging",
    form_message_label: "Message / Inquiry",
    form_message_placeholder: "Please describe the products or services you are looking for...",
    form_submit: "Send Message",
    form_submitting: "Sending...",
    form_success: "Thank you! Your message has been sent successfully. Our team will contact you shortly.",
    form_error: "Oops! Something went wrong. Please try again.",
    form_validation: "Please fill out all required fields.",
    open_maps: "Open in Google Maps",
    // VCI Product Page
    vci_page_title: "Anti-Rust & ESD Packaging",
    vci_title: "Industrial-Grade VCI Anti-Rust Packaging & ESD Solutions",
    vci_intro: "We are experts in anti-corrosion and anti-rust packaging for the industrial sector. We select premium imported raw materials and master rolls, offering made-to-order sizing and designs for the ultimate protection of your metal and electronic components.",
    vci_types_title: "Our Products & Services",
    vci_type1_title: "VCI Anti-Rust Packaging",
    vci_type1_p1: "VCI Bag: Plastic packaging infused with Volatile Corrosion Inhibitors to protect metal parts and machinery from rusting during storage and transport. Clean, safe, and leaves no oily residue.",
    vci_type1_p2: "VCI Paper: High-quality anti-rust wrapping paper, ideal for automotive parts, spare parts, and machine tools.",
    vci_type1_p3: "Custom Sizing: Made-to-order VCI bags and papers tailored to your exact specifications for a perfect fit, reducing packaging waste.",
    vci_type2_title: "Anti-Static Bag",
    vci_type2_desc: "Packaging designed to protect sensitive electronic components and circuit boards from electrostatic discharge, ensuring safety from origin to destination.",
    vci_type3_title: "Industrial Anti-Rust Oil",
    vci_type3_desc: "Premium anti-rust coating oil to protect metal surfaces from moisture and oxidation. Ideal for temporary storage during assembly or long-term preservation.",
    vci_why_title: "Why the Industrial Sector Trusts Us",
    vci_why1_title: "High-Quality Raw Materials",
    vci_why1_desc: "Using premium imported raw materials and master rolls, ensuring superior durability and protection.",
    vci_why2_title: "Customizable Services",
    vci_why2_desc: "Supporting custom-size manufacturing to perfectly match your actual usage requirements.",
    vci_why3_title: "Fast Delivery",
    vci_why3_desc: "Delivery within 2 weeks, ensuring your production line and logistics run continuously.",
    vci_cta_text: "Need a consultation on anti-rust packaging or want to order a custom size?",
    vci_cta_btn: "Contact Sales for Samples / Request a Quote",
    back_home: "Back to Home",
    // Packaging Product Page
    pkg_page_title: "Custom Cartons & Packaging",
    pkg_title: "Custom Printed Cartons and Die-Cut Boxes for Every Brand",
    pkg_intro: "Elevate your products and build brand trust with custom carton and die-cut box manufacturing. Support for logo printing (full color or single color black). We select high-quality, durable paper suitable for products, premium goods, and E-commerce parcels. No minimum order quantity.",
    pkg_features_title: "Features and Services",
    pkg_feat1_title: "Custom Size Cartons and Die-Cut Boxes",
    pkg_feat1_desc: "Designed and tailored to fit your products perfectly, saving cushioning material and creating a professional unboxing experience.",
    pkg_feat2_title: "Custom Logo Printing",
    pkg_feat2_p1: "Full Color: Ideal for brands seeking vibrant, realistic colors that match their Corporate Identity (CI).",
    pkg_feat2_p2: "Single Color / Black: Offers a classic, minimalist feel while effectively controlling production costs.",
    pkg_feat3_title: "Flexible Terms for Your Business",
    pkg_feat3_p1: "No Minimum Order: Perfect for SMEs testing the market or large brands doing limited runs.",
    pkg_feat3_p2: "Fast Production: Delivering quality work within 2 weeks after PO issuance and artwork confirmation.",
    pkg_why_title: "Why Choose Our Packaging Services?",
    pkg_why1_title: "Enhance Brand Image",
    pkg_why1_desc: "Logo-printed boxes add value, making your products look more premium and professional.",
    pkg_why2_title: "Cost-Effective & Exact Specs",
    pkg_why2_desc: "Produced to exact usage sizes, reducing storage space and transport damage.",
    pkg_why3_title: "Fast & Standardized Service",
    pkg_why3_desc: "Strict quality control at every step with on-time delivery.",
    pkg_cta_text: "Want to order custom logo-printed cartons?",
    pkg_cta_btn: "Contact us for consultation & pricing / Send artwork for a quote",
    // O-ring Product Page
    oring_page_title: "Industrial O-Rings, Gaskets & Seals",
    oring_title: "Premium Industrial O-Rings, Gaskets, & Seals for Hydraulics, Pneumatics, and Heavy Machinery",
    oring_intro: "Carefully selected high-quality rubber materials resistant to chemicals, heat, and high pressure, meeting the specific demands of the industrial sector.",
    oring_types_title: "Industrial Product Types",
    oring_type1_title: "O-Ring",
    oring_type1_desc: "Circular rubber gaskets for preventing liquid and gas leaks in machinery joints. Available in various material grades such as NBR, Viton, EPDM, and Silicone to suit specific temperatures and chemicals.",
    oring_type2_title: "Industrial Gasket",
    oring_type2_desc: "Sheet gaskets and custom-cut gaskets for pipe flanges, exhausts, tank covers, and machinery connections, preventing leaks under high pressure.",
    oring_type3_title: "Industrial Seal",
    oring_type3_desc: "Oil seals, hydraulic seals, and various leakage prevention seals that help extend machinery lifespan, reduce wear, and prevent contaminants from entering the system.",
    oring_why_title: "Our Features & Services",
    oring_why1_title: "Industry Standard Materials",
    oring_why1_desc: "Selecting materials resistant to wear, oil, chemicals, and extreme weather conditions.",
    oring_why2_title: "Sourcing & Custom Cutting",
    oring_why2_desc: "Sourcing standard size O-rings and gaskets (AS568, JIS) or cutting according to blueprints and customer samples.",
    oring_why3_title: "Fast Delivery",
    oring_why3_desc: "Supporting your maintenance and production lines to run smoothly without interruption.",
    oring_cta_text: "Looking for special spec O-rings, gaskets, or seals for your machinery?",
    oring_cta_btn: "Contact our Sales Engineering team to inquire about stock and special sizes",
    // Wire Harnesses Product Page
    wire_page_title: "Wire Harnesses & EV Chargers",
    wire_title: "Wire Harnesses, Power Cords & EV Chargers for Automotive & Home Appliances",
    wire_intro: "Manufacturer and supplier of industrial Wire Harnesses meeting Automotive Quality Standards. Covering Home Appliances, Power Cords, and EV Chargers. Providing full engineering support from structural design and routing to sample prototyping before mass production.",
    wire_features_title: "Engineering Support & Services",
    wire_feat1_title: "Design & Routing",
    wire_feat1_desc: "Professional consultation on structural design and routing recommendations for optimal layout.",
    wire_feat2_title: "Mockup Samples",
    wire_feat2_desc: "Mockup sample creation for testing and validation before starting mass production.",
    wire_feat3_title: "Automotive Standard",
    wire_feat3_desc: "Manufacturing processes and quality control that meet the strict requirements of the automotive industry.",
    wire_why_title: "Why Choose Us",
    wire_why1_title: "Comprehensive Range",
    wire_why1_desc: "Covering automotive, home appliances, and electric vehicle charging equipment.",
    wire_why2_title: "Expert Consultation",
    wire_why2_desc: "We are more than just a manufacturer; we provide advice and support at every step.",
    wire_why3_title: "Reliable Quality",
    wire_why3_desc: "Delivering tested, standard-compliant products you can trust.",
    wire_cta_text: "Need custom wire harnesses or EV charging cables for your project?",
    wire_cta_btn: "Contact our Engineering Sales team for consultation and prototyping",
    // Chemical Product Page
    chem_page_title: "Industrial & Lab Chemicals",
    chem_title: "Comprehensive Industrial & Lab Chemicals",
    chem_intro: "We provide sourcing and import services for high-quality chemicals for industrial and laboratory sectors. Covering a wide range of grades including Industrial Grade, Lab Grade, Medical Grade, and other specialized chemicals. We also offer OEM chemical formulation services tailored to customer needs. Ensure safety with official certificates and testing reports from leading institutions.",
    chem_features_title: "Chemical Types & Grades We Provide",
    chem_feat1_title: "Industrial Grade",
    chem_feat1_desc: "Chemicals for manufacturing processes, industrial plants, and raw materials for molding.",
    chem_feat2_title: "Lab & Medical Grade",
    chem_feat2_desc: "High-purity chemicals for analysis, research, quality control in labs, and the medical industry.",
    chem_feat3_title: "OEM Formula Development",
    chem_feat3_desc: "Inventing and developing new chemical formulas based on specific customer requirements, with expert consultation.",
    chem_why_title: "Features & Service Standards",
    chem_why1_title: "Global Sourcing",
    chem_why1_desc: "Sourcing and importing chemicals of all grades from international standard manufacturers.",
    chem_why2_title: "Custom Formulation",
    chem_why2_desc: "Supporting research and development of new products to create business advantages.",
    chem_why3_title: "Certified Standards",
    chem_why3_desc: "Delivered with COA, MSDS/SDS, and test reports from reliable institutions for transparency and maximum safety.",
    chem_cta_text: "Looking for special grade chemicals or want to develop a new product formula (OEM)?",
    chem_cta_btn: "Consult our Chemical Experts / Request a Quote",
    // Motor & Drive Product Page
    motor_page_title: "Motor & Drive",
    motor_title: "Canworld VFD Inverters - Exclusive Importer & Distributor in Thailand",
    motor_intro: "Optimize machinery performance and precise control with VFD Inverters (Variable Frequency Drives) from Canworld. We are trusted as the <strong>Exclusive Importer and Distributor in Thailand</strong>, importing directly from China. Available in both V/F Control and Vector Control systems, supporting various industrial applications with fast delivery and superior warranty terms.",
    motor_features_title: "Capacity Range",
    motor_feat1_title: "Single-Phase 220V",
    motor_feat1_desc: "Supports power from 0.75kW to 2.2kW",
    motor_feat2_title: "Three-Phase 380V / 480V",
    motor_feat2_desc: "Supports power from 1.5kW to 1250kW (covering small industries to large-scale factories)",
    motor_why_title: "Why Choose Us",
    motor_why1_title: "Exclusive Distributor",
    motor_why1_desc: "As the sole official distributor of Canworld in Thailand, you can be confident in our quality and after-sales service.",
    motor_why2_title: "Fast Delivery & Import",
    motor_why2_desc: "<strong>In-stock in Thailand:</strong> Immediate delivery within 1 day.<br><strong>Pre-orders:</strong> Direct air freight from Shenzhen, China, delivered within 7 days (min. 1 piece).<br><strong>DDP Terms:</strong> Air freight and all taxes included.",
    motor_why3_title: "18-Month Warranty",
    motor_why3_desc: "<strong>Greater confidence with an extended 18-month warranty. Immediate replacement for any defective products.</strong>",
    motor_cta_text: "Looking for high-quality VFD Inverters with full after-sales service?",
    motor_cta_btn: "Check Stock / Request a Quote and Technical Consultation"
  },
  th: {
    nav_home: "หน้าแรก",
    nav_about: "เกี่ยวกับเรา",
    nav_products: "สินค้าและบริการ",
    nav_contact: "ติดต่อเรา",
    hero_headline: "โซลูชันการจัดหาสินค้าและคู่ค้าเชิงยุทธศาสตร์ระดับโลก",
    hero_subhead: "บริการนำเข้า ส่งออก และจัดหาสินค้าอุตสาหกรรมภายในประเทศ เชื่อมต่อธุรกิจของคุณกับซัพพลายเชนคุณภาพสูงทั่วโลก",
    hero_cta: "ดูบริการของเรา",
    about_title: "เกี่ยวกับ ออคโต โนโตะ",
    about_desc: "บริษัทการค้าชั้นนำในประเทศไทย ที่มีความเชี่ยวชาญด้านการจัดหาเชิงเทคนิค การควบคุมคุณภาพ และการจัดการซัพพลายเชนระหว่างประเทศ เราทำหน้าที่เป็นพันธมิตรเชิงยุทธศาสตร์เพื่อให้มั่นใจว่าลูกค้าของเราได้รับสินค้าที่เหมาะสมที่สุดสำหรับการใช้งานเฉพาะด้าน",
    val_1_title: "การจัดหาเชิงเทคนิค",
    val_1_desc: "ให้คำปรึกษาเพื่อหาสินค้าที่ตรงความต้องการ",
    val_2_title: "คุณภาพต้องมาก่อน",
    val_2_desc: "ตรวจสอบผู้ผลิตและควบคุมคุณภาพอย่างเข้มงวด",
    val_3_title: "พันธมิตรเชิงยุทธศาสตร์",
    val_3_desc: "เน้นคุณค่าระยะยาว ความน่าเชื่อถือ และราคาที่โปร่งใส",
    prod_title: "สินค้าและบริการ",
    prod_1: "บรรจุภัณฑ์กันสนิมและอุปกรณ์ป้องกันไฟฟ้าสถิต",
    prod_2: "วัสดุบรรจุภัณฑ์ กล่องกระดาษ และฟิล์มยืด",
    prod_3: "โอริง ปะเก็น และซีลอุตสาหกรรม",
    prod_4: "ชุดสายไฟ สายไฟ และเครื่องชาร์จรถยนต์ไฟฟ้า",
    prod_5: "เคมีภัณฑ์สำหรับอุตสาหกรรมและห้องปฏิบัติการ",
    prod_7: "มอเตอร์และระบบขับเคลื่อน (Motor & Drive)",
    prod_group_industrial: "สินค้าอุตสาหกรรม",
    prod_group_inhouse: "แบรนด์ภายในองค์กร (Inhouse Brand)",
    inhouse_prod_1: "The White Ivory (เร็วๆ นี้)",
    catalogue_title: "ดาวน์โหลดแคตตาล็อก",
    catalogue_desc: "สแกนคิวอาร์โค้ดหรือคลิกปุ่มด้านล่างเพื่อดูแคตตาล็อกสินค้าทั้งหมดของเรา",
    catalogue_btn: "ดาวน์โหลดผ่าน Google Drive",
    contact_title: "ติดต่อเรา",
    contact_company: "บริษัท ออคโต โนโตะ จำกัด",
    contact_address: "88/206 หมู่บ้าน แกรนด์พลีโน สุขสวัสดิ์-พระราม3 ประชาอุทิศ 54 เขตทุ่งครุ กรุงเทพมหานคร 10140",
    footer_copy: "© 2026 OCTO NOTO CO., LTD. สงวนลิขสิทธิ์",
    form_name_label: "ชื่อ-นามสกุล",
    form_name_placeholder: "สมชาย ใจดี",
    form_company_label: "ชื่อบริษัท",
    form_company_placeholder: "บริษัท ของคุณ จำกัด",
    form_email_label: "อีเมล",
    form_email_placeholder: "somchai@example.com",
    form_phone_label: "เบอร์โทรศัพท์",
    form_phone_placeholder: "081-234-5678",
    form_subject_label: "หัวข้อติดต่อ",
    form_subject_placeholder: "สอบถามเรื่องบรรจุภัณฑ์กันสนิม",
    form_message_label: "ข้อความ / รายละเอียดสินค้าที่ต้องการให้จัดหา",
    form_message_placeholder: "โปรดระบุรายละเอียดสินค้า หรือบริการที่คุณกำลังมองหา...",
    form_submit: "ส่งข้อความ",
    form_submitting: "กำลังส่ง...",
    form_success: "ขอบคุณค่ะ! ระบบได้ส่งข้อมูลของท่านเรียบร้อยแล้ว เจ้าหน้าที่ของเราจะติดต่อกลับโดยเร็วที่สุด",
    form_error: "เกิดข้อผิดพลาดบางอย่าง กรุณาลองใหม่อีกครั้ง",
    form_validation: "กรุณากรอกข้อมูลในช่องที่กำหนดให้ครบถ้วน",
    open_maps: "เปิดบน Google Maps",
    // VCI Product Page
    vci_page_title: "บรรจุภัณฑ์กันสนิมและอุปกรณ์ป้องกันไฟฟ้าสถิต",
    vci_title: "โซลูชันบรรจุภัณฑ์กันสนิม ถุง VCI และวัสดุป้องกันไฟฟ้าสถิตมาตรฐานอุตสาหกรรม",
    vci_intro: "เราคือผู้เชี่ยวชาญด้านบรรจุภัณฑ์ป้องกันการกัดกร่อนและสนิมสำหรับภาคอุตสาหกรรม คัดสรรวัตถุดิบและ Master Roll เกรดพรีเมียมนำเข้าจากต่างประเทศ พร้อมให้บริการตัดแต่งตามขนาดและรูปแบบที่ลูกค้าต้องการ (Made-to-Order) เพื่อการปกป้องชิ้นส่วนโลหะและอิเล็กทรอนิกส์อย่างมีประสิทธิภาพสูงสุด",
    vci_types_title: "ประเภทผลิตภัณฑ์และบริการของเรา",
    vci_type1_title: "บรรจุภัณฑ์ป้องกันสนิมเทคโนโลยี VCI (VCI Anti-Rust Packaging)",
    vci_type1_p1: "ถุงกันสนิม (VCI Bag): ถุงพลาสติกบรรจุภัณฑ์ผสมสารระเหยยับยั้งสนิม (Volatile Corrosion Inhibitor) ช่วยปกป้องชิ้นส่วนโลหะและเครื่องจักรไม่ให้เกิดสนิมระหว่างการจัดเก็บและการขนส่ง สะอาด ปลอดภัย ไม่ทิ้งคราบมันบนพื้นผิวชิ้นงาน",
    vci_type1_p2: "กระดาษกันสนิม (VCI Paper): กระดาษห่อกันสนิมคุณภาพสูง เหมาะสำหรับการห่อหุ้มชิ้นส่วนยานยนต์ อะไหล่ และเครื่องมือกล",
    vci_type1_p3: "บริการตัดตามขนาด: รับผลิตและตัดถุงกันสนิม กระดาษกันสนิม ตามขนาดและสเปกเฉพาะของลูกค้า เพื่อให้ใช้งานได้พอดีกับชิ้นงาน ลดขยะบรรจุภัณฑ์",
    vci_type2_title: "ถุงกันไฟฟ้าสถิต (Anti-Static Bag)",
    vci_type2_desc: "บรรจุภัณฑ์ป้องกันความเสียหายจากประจุไฟฟ้าสถิตสำหรับอุตสาหกรรมอิเล็กทรอนิกส์ แผงวงจร และอุปกรณ์ที่มีความอ่อนไหว ป้องกันความเสียหายตั้งแต่ต้นทางจนถึงมือผู้รับ",
    vci_type3_title: "น้ำมันกันสนิมอุตสาหกรรม (Anti-Rust Oil)",
    vci_type3_desc: "น้ำมันเคลือบป้องกันสนิมคุณภาพเยี่ยม ช่วยเคลือบผิวโลหะเพื่อป้องกันความชื้นและการเกิดออกซิเดชัน เหมาะสำหรับงานพักผิวชิ้นงานระหว่างรอประกอบหรือเก็บรักษาในระยะยาว",
    vci_why_title: "จุดเด่นที่เราได้รับความไว้วางใจจากภาคอุตสาหกรรม",
    vci_why1_title: "Raw Material คุณภาพสูง",
    vci_why1_desc: "ใช้วัตถุดิบและ Master Roll นำเข้าจากต่างประเทศ มั่นใจได้ในมาตรฐานความทนทานและการปกป้อง",
    vci_why2_title: "บริการตัดแต่งตามความต้องการ",
    vci_why2_desc: "รองรับการผลิตตามขนาด (Custom Size) ที่ลูกค้าต้องการใช้งานจริง",
    vci_why3_title: "ส่งมอบรวดเร็ว",
    vci_why3_desc: "บริการจัดส่งสินค้าถึงมือลูกค้าภายใน 2 สัปดาห์ ช่วยให้สายการผลิตและการขนส่งของคุณดำเนินไปได้อย่างต่อเนื่อง",
    vci_cta_text: "ต้องการปรึกษาเรื่องบรรจุภัณฑ์กันสนิม หรือสั่งตัดตามขนาดพิเศษ?",
    vci_cta_btn: "ติดต่อทีมงานฝ่ายขายเพื่อขอตัวอย่างสินค้า / ขอใบเสนอราคา",
    back_home: "กลับสู่หน้าหลัก",
    // Packaging Product Page
    pkg_page_title: "กล่องกระดาษและกล่องไดคัทพิมพ์ลายตามสั่ง",
    pkg_title: "กล่องกระดาษและกล่องไดคัทพิมพ์ลายตามสั่ง ตอบโจทย์ทุกบรรจุภัณฑ์แบรนด์คุณ",
    pkg_intro: "ยกระดับสินค้าและสร้างความน่าเชื่อถือให้กับแบรนด์ด้วยบริการผลิต กล่องกระดาษ และ กล่องไดคัท ตามขนาดและดีไซน์เฉพาะตัว รองรับการพิมพ์โลโก้หรือลวดลายตามความต้องการ (พิมพ์สีคมชัด หรือพิมพ์ดำสีเดียว) คัดสรรวัสดุกระดาษคุณภาพดี แข็งแรงทนทาน เหมาะสำหรับใส่สินค้า ผลิตภัณฑ์พรีเมียม และกล่องพัสดุ E-commerce พร้อมให้บริการด้วยความใส่ใจ ไม่มีขั้นต่ำในการสั่งผลิต",
    pkg_features_title: "ลักษณะเด่นและบริการของเรา",
    pkg_feat1_title: "กล่องไดคัทและกล่องกระดาษสั่งทำตามขนาด (Custom Size)",
    pkg_feat1_desc: "ออกแบบและตัดเย็บรูปทรงกล่องให้พอดีกับสินค้าของคุณ ช่วยประหยัดวัสดุกันกระแทก ดูเป็นมืออาชีพ และสร้างความประทับใจแรกพบเมื่อลูกค้าเปิดกล่อง (Unboxing Experience)",
    pkg_feat2_title: "บริการพิมพ์โลโก้และลวดลายแบรนด์คุณ (Logo Printing)",
    pkg_feat2_p1: "พิมพ์สีคมชัด: เหมาะสำหรับแบรนด์ที่ต้องการความโดดเด่น สีสันสวยงาม สมจริง ตรงตามCorporate Identity (CI)",
    pkg_feat2_p2: "พิมพ์ดำสีเดียว (Single Color / Black): ให้ความรู้สึกเรียบหรู คลาสสิก มินิมอล และช่วยควบคุมต้นทุนการผลิตได้อย่างมีประสิทธิภาพ",
    pkg_feat3_title: "ยืดหยุ่นด้วยเงื่อนไขที่ตอบโจทย์ธุรกิจ",
    pkg_feat3_p1: "ไม่มีขั้นต่ำ (No Minimum Order): รองรับทั้งธุรกิจขนาดเล็ก (SMEs) ที่ต้องการทดลองตลาด หรือแบรนด์ใหญ่ที่ต้องการผลิตจำนวนจำกัด",
    pkg_feat3_p2: "ระยะเวลาการผลิตที่รวดเร็ว: พร้อมส่งมอบงานคุณภาพภายใน 2 สัปดาห์ หลังจากที่ลูกค้าเปิดคำสั่งซื้อ (PO) และยืนยันความถูกต้องของแบบพิมพ์ (Artwork) เป็นที่เรียบร้อยแล้ว",
    pkg_why_title: "ทำไมต้องเลือกใช้บริการกล่องบรรจุภัณฑ์ของเรา?",
    pkg_why1_title: "เสริมภาพลักษณ์แบรนด์",
    pkg_why1_desc: "กล่องพิมพ์โลโก้ช่วยเพิ่มมูลค่าให้สินค้าดูพรีเมียมและเป็นมืออาชีพยิ่งขึ้น",
    pkg_why2_title: "คุ้มค่า ตรงสเปก",
    pkg_why2_desc: "ผลิตตามขนาดที่ใช้งานจริง ลดพื้นที่จัดเก็บและลดความเสียหายระหว่างขนส่ง",
    pkg_why3_title: "บริการรวดเร็วและได้มาตรฐาน",
    pkg_why3_desc: "ควบคุมคุณภาพการผลิตทุกขั้นตอน พร้อมจัดส่งตรงเวลา",
    pkg_cta_text: "ต้องการสั่งผลิตกล่องกระดาษพิมพ์โลโก้ตามขนาดของคุณ?",
    pkg_cta_btn: "ติดต่อทีมงานเพื่อปรึกษาขนาดและประเมินราคา / ส่งแบบพิมพ์เพื่อขอใบเสนอราคา",
    // O-ring Product Page
    oring_page_title: "โอริง ปะเก็น และซีลอุตสาหกรรม",
    oring_title: "โอริง ปะเก็น และซีลอุตสาหกรรมเกรดพรีเมียม ตอบโจทย์ทุกการใช้งานในระบบไฮดรอลิก นิวเมติกส์ และเครื่องจักรกลหนัก",
    oring_intro: "คัดสรรวัสดุยางคุณภาพสูงทนทานต่อสารเคมี ความร้อน และแรงดันสูง รองรับความต้องการเฉพาะของภาคอุตสาหกรรม",
    oring_types_title: "ประเภทผลิตภัณฑ์อุตสาหกรรม",
    oring_type1_title: "โอริง (O-Ring)",
    oring_type1_desc: "ปะเก็นยางวงกลมสำหรับป้องกันการรั่วไหลของของเหลวและก๊าซในข้อต่อเครื่องจักร มีหลากหลายเกรดวัสดุ เช่น NBR, Viton, EPDM และ Silicone เพื่อให้เหมาะสมกับอุณหภูมิและสารเคมีเฉพาะงาน",
    oring_type2_title: "ปะเก็นอุตสาหกรรม (Gasket)",
    oring_type2_desc: "ปะเก็นแผ่นและปะเก็นตัดตามแบบ สำหรับหน้าแปลนท่อ ท่อไอเสีย ฝาครอบถัง และจุดเชื่อมต่อเครื่องจักร ป้องกันการรั่วซึมภายใต้แรงดันสูง",
    oring_type3_title: "ซีลอุตสาหกรรม (Industrial Seal)",
    oring_type3_desc: "ซีลน้ำมัน ซีลไฮดรอลิก และซีลกันรั่วประเภทต่างๆ ช่วยยืดอายุการใช้งานของเครื่องจักร ลดการสึกหรอ และป้องกันสิ่งแปลกปลอมเข้าสู่ระบบ",
    oring_why_title: "จุดเด่นและบริการของเรา",
    oring_why1_title: "วัสดุมาตรฐานอุตสาหกรรม",
    oring_why1_desc: "เลือกใช้วัสดุที่ทนทานต่อการสึกหรอ น้ำมัน สารเคมี และสภาพอากาศที่รุนแรง",
    oring_why2_title: "บริการจัดหาและตัดตามสเปก",
    oring_why2_desc: "รองรับการจัดหาโอริงและปะเก็นตามขนาดมาตรฐาน (AS568, JIS) หรือตัดตามแบบพิมพ์เขียวและตัวอย่างของลูกค้า",
    oring_why3_title: "บริการจัดส่งรวดเร็ว",
    oring_why3_desc: "สนับสนุนการซ่อมบำรุงและสายการผลิตของคุณให้ดำเนินต่อไปได้อย่างไม่สะดุด",
    oring_cta_text: "กำลังมองหาโอริง ปะเก็น หรือซีลสเปกพิเศษสำหรับเครื่องจักรของคุณอยู่ใช่ไหม?",
    oring_cta_btn: "ติดต่อทีมงานวิศวกรฝ่ายขายเพื่อสอบถามสต็อกสินค้าและขนาดพิเศษ",
    // Wire Harnesses Product Page
    wire_page_title: "ชุดสายไฟ สายไฟ และเครื่องชาร์จรถยนต์ไฟฟ้า",
    wire_title: "Wire Harnesses, Power Cords และ EV Chargers มาตรฐานสุตสาหกรรมยานยนต์และเครื่องใช้ไฟฟ้า",
    wire_intro: "ผู้ผลิตและจัดหาชุดสายไฟอุตสาหกรรม (Wire Harnesses) ที่ได้มาตรฐานระบบคุณภาพยานยนต์ (Automotive Standard) ครอบคลุมถึงกลุ่มเครื่องใช้ไฟฟ้าในบ้าน (Home Appliance) สายไฟพาวเวอร์คอร์ด (Power Cords) รวมถึงอุปกรณ์ชาร์จรถยนต์ไฟฟ้า (EV Chargers) และแวดวงยานยนต์ไฟฟ้าอย่างครบวงจร",
    wire_features_title: "บริการซัพพอร์ตด้านวิศวกรรม (Engineering Support)",
    wire_feat1_title: "การออกแบบและจัดวาง (Design & Routing)",
    wire_feat1_desc: "บริการให้คำปรึกษา ออกแบบโครงสร้างและการจัดวางสายไฟให้เหมาะสมกับการใช้งาน",
    wire_feat2_title: "การจัดทำชิ้นงานตัวอย่าง (Mockup Sample)",
    wire_feat2_desc: "รับจัดทำชิ้นงานตัวอย่างสำหรับทดสอบความถูกต้องและประสิทธิภาพก่อนเริ่มการผลิตจริง (Mass Production)",
    wire_feat3_title: "มาตรฐานยานยนต์ (Automotive Standard)",
    wire_feat3_desc: "กระบวนการผลิตและควบคุมคุณภาพเทียบเท่ามาตรฐานอุตสาหกรรมยานยนต์",
    wire_why_title: "ทำไมถึงต้องเลือกเรา",
    wire_why1_title: "ครบวงจร",
    wire_why1_desc: "ครอบคลุมทั้งยานยนต์ เครื่องใช้ไฟฟ้า และอุปกรณ์ชาร์จ EV",
    wire_why2_title: "พร้อมให้คำปรึกษา",
    wire_why2_desc: "เราไม่ได้เป็นเพียงผู้ผลิต แต่พร้อมเป็นผู้ช่วยให้คำปรึกษาในทุกขั้นตอน",
    wire_why3_title: "คุณภาพเชื่อถือได้",
    wire_why3_desc: "ส่งมอบงานคุณภาพที่ผ่านการทดสอบและได้มาตรฐาน",
    wire_cta_text: "ต้องการออกแบบหรือสั่งผลิตชุดสายไฟและเครื่องชาร์จ EV ใช่ไหม?",
    wire_cta_btn: "ติดต่อวิศวกรของเราเพื่อปรึกษาและขอรับชิ้นงานตัวอย่าง",
    // Chemical Product Page
    chem_page_title: "เคมีภัณฑ์สำหรับอุตสาหกรรมและห้องปฏิบัติการ",
    chem_title: "สารเคมีอุตสาหกรรมและห้องปฏิบัติการครบวงจร",
    chem_intro: "บริการจัดหาและนำเข้าสารเคมีคุณภาพสูงสำหรับภาคอุตสาหกรรมและห้องปฏิบัติการ (Industrial & Lab Chemicals) ครอบคลุมหลากหลายเกรดการใช้งาน ไม่ว่าจะเป็นสารเคมีเกรดอุตสาหกรรมทั่วไป, เกรดห้องปฏิบัติการ (Lab Grade), เกรดการแพทย์ (Medical Grade) รวมถึงสารเคมีเฉพาะทางอื่นๆ พร้อมบริการรับพัฒนาสูตรผลิตภัณฑ์ใหม่ตามความต้องการของลูกค้าในรูปแบบ OEM มั่นใจได้ในมาตรฐานความปลอดภัยด้วยเอกสารรับรองและผลการทดสอบอย่างเป็นทางการจากสถาบันทดสอบชั้นนำ",
    chem_features_title: "ประเภทและเกรดสารเคมีที่เราให้บริการ",
    chem_feat1_title: "สารเคมีเกรดอุตสาหกรรม (Industrial Grade)",
    chem_feat1_desc: "สารเคมีสำหรับกระบวนการผลิต โรงงานอุตสาหกรรม และสารตั้งต้นสำหรับงานขึ้นรูปต่างๆ",
    chem_feat2_title: "สารเคมีเกรดห้องปฏิบัติการและเครื่องมือแพทย์ (Lab & Medical Grade)",
    chem_feat2_desc: "เคมีภัณฑ์ความบริสุทธิ์สูงสำหรับงานวิเคราะห์ วิจัย ควบคุมคุณภาพในห้อง Lab และอุตสาหกรรมการแพทย์",
    chem_feat3_title: "บริการพัฒนาสูตรเคมี (OEM Formula Development)",
    chem_feat3_desc: "รับคิดค้นและพัฒนาสูตรสารเคมีใหม่ตามโจทย์เฉพาะของลูกค้า พร้อมให้คำปรึกษาโดยผู้เชี่ยวชาญ",
    chem_why_title: "จุดเด่นและมาตรฐานการบริการ",
    chem_why1_title: "บริการจัดหาเคมีนำเข้าทั่วโลก",
    chem_why1_desc: "สามารถสรรหาและนำเข้าสารเคมีทุกเกรดที่ลูกค้าต้องการจากแหล่งผลิตมาตรฐานสากล",
    chem_why2_title: "พัฒนาสูตรเฉพาะ (Custom Formulation)",
    chem_why2_desc: "รองรับงานวิจัยและพัฒนาผลิตภัณฑ์ใหม่เพื่อสร้างความได้เปรียบทางธุรกิจ",
    chem_why3_title: "เอกสารรับรองมาตรฐาน (Certificate & Testing Reports)",
    chem_why3_desc: "มาพร้อม COA, MSDS/SDS และเอกสารรับรองผลการทดสอบจากสถาบันทดสอบที่น่าเชื่อถือ เพื่อความโปร่งใสและปลอดภัยสูงสุดในกระบวนการผลิต",
    chem_cta_text: "กำลังมองหาสารเคมีเกรดพิเศษ หรือต้องการพัฒนาสูตรผลิตภัณฑ์ใหม่ในรูปแบบ OEM?",
    chem_cta_btn: "ปรึกษาทีมผู้เชี่ยวชาญด้านเคมีภัณฑ์ / ขอใบเสนอราคาและเอกสารรับรอง",
    // Motor & Drive Product Page
    motor_page_title: "มอเตอร์และระบบขับเคลื่อน (Motor & Drive)",
    motor_title: "VFD Inverter (ตัวปรับรอบความเร็วมอเตอร์) แบรนด์ Canworld ผู้นำเข้าและตัวแทนจำหน่ายแต่เพียงผู้เดียวในไทย",
    motor_intro: "เพิ่มประสิทธิภาพและควบคุมการทำงานของเครื่องจักรอย่างแม่นยำด้วย VFD Inverter (Variable Frequency Drive) จากแบรนด์ Canworld เราได้รับความไว้วางใจให้เป็น <strong>ผู้นำเข้าและตัวแทนจำหน่ายแต่เพียงผู้เดียวในประเทศไทย (Exclusive Distributor)</strong> นำเข้าโดยตรงจากประเทศจีน มีให้เลือกใช้งานทั้งระบบควบคุมแบบ V/F Control และ Vector Control รองรับงานอุตสาหกรรมหลากหลายรูปแบบ พร้อมบริการจัดส่งรวดเร็วและเงื่อนไขการรับประกันที่เหนือกว่า",
    motor_features_title: "ช่วงกำลังการผลิต (Capacity Range)",
    motor_feat1_title: "Single-Phase 220V",
    motor_feat1_desc: "รองรับกำลังไฟตั้งแต่ 0.75kW ถึง 2.2kW",
    motor_feat2_title: "Three-Phase 380V / 480V",
    motor_feat2_desc: "รองรับกำลังไฟตั้งแต่ 1.5kW ถึง 1250kW (ครอบคลุมงานอุตสาหกรรมขนาดเล็กจนถึงโรงงานขนาดใหญ่)",
    motor_why_title: "จุดเด่นและบริการของเรา",
    motor_why1_title: "Exclusive Brand",
    motor_why1_desc: "เป็นตัวแทนจำหน่ายอย่างเป็นทางการแต่เพียงผู้เดียวในประเทศไทยของแบรนด์ Canworld มั่นใจได้ในคุณภาพและบริการหลังการขาย",
    motor_why2_title: "สต็อกพร้อมส่ง และนำเข้ารวดเร็ว",
    motor_why2_desc: "<strong>สินค้ามีสต๊อคในไทย:</strong> จัดส่งสินค้าทันทีภายใน 1 วัน<br><strong>สินค้าพรีออร์เดอร์:</strong> จัดส่งด่วนทางเครื่องบินจากเมืองเซินเจิ้น ประเทศจีน ถึงมือท่านภายใน 7 วัน (ขั้นต่ำ 1 ชิ้น)<br><strong>เงื่อนไข DDP:</strong> รวมค่าขนส่งและภาษีทุกอย่างเรียบร้อยแล้ว",
    motor_why3_title: "การรับประกันสินค้า 18 เดือน",
    motor_why3_desc: "<strong>มั่นใจยิ่งขึ้นด้วยการรับประกันสินค้ายาวนานถึง 18 เดือน สินค้ามีปัญหาเปลี่ยนใหม่ให้ทันที</strong>",
    motor_cta_text: "กำลังมองหา VFD Inverter ควบคุมรอบมอเตอร์คุณภาพสูง พร้อมบริการหลังการขายเต็มรูปแบบ?",
    motor_cta_btn: "ตรวจสอบสต็อกสินค้า / ขอใบเสนอราคาและปรึกษาทีมวิศวกรเทคนิค"
  }
};
