const translations = {
  en: {
    nav_home: "Home",
    nav_about: "About Us",
    nav_products: "Products & Services",
    nav_contact: "Contact Us",
    hero_headline: "Global Sourcing & Strategic Trading Solutions",
    hero_subhead: "Import, Export, and Domestic Industrial Solutions. Connecting businesses with high-quality global supply chains.",
    hero_cta: "Explore Our Solutions",
    about_title: "About OCTO NOTO",
    about_desc: "A premier Thai-based trading house specializing in technical sourcing, quality control, and international supply chain management. We act as a strategic partner to ensure our clients get the right product for their specific application.",
    val_1_title: "Technical Sourcing",
    val_1_desc: "Consultation to find the exact match.",
    val_2_title: "Quality First",
    val_2_desc: "Rigorous supplier vetting and quality control.",
    val_3_title: "Strategic Partner",
    val_3_desc: "Long-term value, reliability, and transparent pricing.",
    prod_title: "Products & Services",
    prod_1: "Anti-Rust Packaging (VCI) & ESD Materials",
    prod_2: "Packing Materials & Cartons",
    prod_3: "Industrial O-Rings, Gaskets, & Seals",
    prod_4: "Wire Harnesses, Power Cords, & EV Chargers",
    prod_5: "Industrial & Lab Chemicals",
    prod_6: "Designed Screws & Connectors",
    prod_7: "Motor & Drive",
    prod_8: "Factory Safety Equipment",
    prod_group_industrial: "Industrial Solutions",
    prod_group_inhouse: "Inhouse Brands",
    inhouse_prod_1: "The White Ivory (Coming Soon)",
    contact_title: "Contact Us",
    contact_company: "OCTO NOTO CO., LTD.",
    contact_address: "88/206 Grande Pleno Suksawat-Rama 3, Pracha Uthit 54, Thung Khru District, Bangkok 10140, Thailand",
    footer_copy: "© 2026 OCTO NOTO CO., LTD. All Rights Reserved.",
    form_name_label: "Full Name",
    form_name_placeholder: "John Doe",
    form_company_label: "Company Name",
    form_company_placeholder: "Your Company Ltd.",
    form_email_label: "Email Address",
    form_email_placeholder: "john@example.com",
    form_phone_label: "Phone Number",
    form_phone_placeholder: "+1 234 567 8900",
    form_subject_label: "Subject",
    form_subject_placeholder: "Inquiry about VCI Packaging",
    form_message_label: "Message / Inquiry",
    form_message_placeholder: "Please describe the products or services you are looking for...",
    form_submit: "Send Message",
    form_submitting: "Sending...",
    form_success: "Thank you! Your message has been sent successfully. Our team will contact you shortly.",
    form_error: "Oops! Something went wrong. Please try again.",
    form_validation: "Please fill out all required fields.",
    open_maps: "Open in Google Maps"
  },
  th: {
    nav_home: "หน้าแรก",
    nav_about: "เกี่ยวกับเรา",
    nav_products: "สินค้าและบริการ",
    nav_contact: "ติดต่อเรา",
    hero_headline: "โซลูชันการจัดหาสินค้าและคู่ค้าเชิงยุทธศาสตร์ระดับโลก",
    hero_subhead: "บริการนำเข้า ส่งออก และจัดหาสินค้าอุตสาหกรรมภายในประเทศ เชื่อมต่อธุรกิจของคุณกับซัพพลายเชนคุณภาพสูงทั่วโลก",
    hero_cta: "ดูบริการของเรา",
    about_title: "เกี่ยวกับ ออคโต โนโตะ",
    about_desc: "บริษัทการค้าชั้นนำในประเทศไทย ที่มีความเชี่ยวชาญด้านการจัดหาเชิงเทคนิค การควบคุมคุณภาพ และการจัดการซัพพลายเชนระหว่างประเทศ เราทำหน้าที่เป็นพันธมิตรเชิงยุทธศาสตร์เพื่อให้มั่นใจว่าลูกค้าของเราได้รับสินค้าที่เหมาะสมที่สุดสำหรับการใช้งานเฉพาะด้าน",
    val_1_title: "การจัดหาเชิงเทคนิค",
    val_1_desc: "ให้คำปรึกษาเพื่อหาสินค้าที่ตรงความต้องการ",
    val_2_title: "คุณภาพต้องมาก่อน",
    val_2_desc: "ตรวจสอบผู้ผลิตและควบคุมคุณภาพอย่างเข้มงวด",
    val_3_title: "พันธมิตรเชิงยุทธศาสตร์",
    val_3_desc: "เน้นคุณค่าระยะยาว ความน่าเชื่อถือ และราคาที่โปร่งใส",
    prod_title: "สินค้าและบริการ",
    prod_1: "บรรจุภัณฑ์กันสนิมและอุปกรณ์ป้องกันไฟฟ้าสถิต",
    prod_2: "วัสดุบรรจุภัณฑ์ กล่องกระดาษ และฟิล์มยืด",
    prod_3: "โอริง ปะเก็น และซีลอุตสาหกรรม",
    prod_4: "ชุดสายไฟ สายไฟ และเครื่องชาร์จรถยนต์ไฟฟ้า",
    prod_5: "เคมีภัณฑ์สำหรับอุตสาหกรรมและห้องปฏิบัติการ",
    prod_6: "สกรูออกแบบพิเศษและข้อต่ออุตสาหกรรม",
    prod_7: "มอเตอร์และระบบขับเคลื่อน (Motor & Drive)",
    prod_8: "อุปกรณ์เซฟตี้ในโรงงาน (Factory Safety Equipment)",
    prod_group_industrial: "สินค้าอุตสาหกรรม",
    prod_group_inhouse: "แบรนด์ภายในองค์กร (Inhouse Brand)",
    inhouse_prod_1: "The White Ivory (เร็วๆ นี้)",
    contact_title: "ติดต่อเรา",
    contact_company: "บริษัท ออคโต โนโตะ จำกัด",
    contact_address: "88/206 หมู่บ้าน แกรนด์พลีโน สุขสวัสดิ์-พระราม3 ประชาอุทิศ 54 เขตทุ่งครุ กรุงเทพมหานคร 10140",
    footer_copy: "© 2026 OCTO NOTO CO., LTD. สงวนลิขสิทธิ์",
    form_name_label: "ชื่อ-นามสกุล",
    form_name_placeholder: "สมชาย ใจดี",
    form_company_label: "ชื่อบริษัท",
    form_company_placeholder: "บริษัท ของคุณ จำกัด",
    form_email_label: "อีเมล",
    form_email_placeholder: "somchai@example.com",
    form_phone_label: "เบอร์โทรศัพท์",
    form_phone_placeholder: "081-234-5678",
    form_subject_label: "หัวข้อติดต่อ",
    form_subject_placeholder: "สอบถามเรื่องบรรจุภัณฑ์กันสนิม",
    form_message_label: "ข้อความ / รายละเอียดสินค้าที่ต้องการให้จัดหา",
    form_message_placeholder: "โปรดระบุรายละเอียดสินค้า หรือบริการที่คุณกำลังมองหา...",
    form_submit: "ส่งข้อความ",
    form_submitting: "กำลังส่ง...",
    form_success: "ขอบคุณค่ะ! ระบบได้ส่งข้อมูลของท่านเรียบร้อยแล้ว เจ้าหน้าที่ของเราจะติดต่อกลับโดยเร็วที่สุด",
    form_error: "เกิดข้อผิดพลาดบางอย่าง กรุณาลองใหม่อีกครั้ง",
    form_validation: "กรุณากรอกข้อมูลในช่องที่กำหนดให้ครบถ้วน",
    open_maps: "เปิดบน Google Maps"
  }
};
