const translations = {
  en: {
    nav_home: "Home",
    nav_about: "About Us",
    nav_products: "Products & Services",
    nav_contact: "Contact Us",
    hero_headline: "Global Sourcing & Strategic Trading Solutions",
    hero_subhead: "Import, Export, and Domestic Industrial Solutions. Connecting businesses with high-quality global supply chains.",
    hero_cta: "Explore Our Solutions",
    about_title: "About OCTO NOTO",
    about_desc: "A premier Thai-based trading house specializing in technical sourcing, quality control, and international supply chain management. We act as a strategic partner to ensure our clients get the right product for their specific application.",
    val_1_title: "Technical Sourcing",
    val_1_desc: "Consultation to find the exact match.",
    val_2_title: "Quality First",
    val_2_desc: "Rigorous supplier vetting and quality control.",
    val_3_title: "Strategic Partner",
    val_3_desc: "Long-term value, reliability, and transparent pricing.",
    prod_title: "Products & Services",
    prod_1: "Anti-Rust Packaging (VCI) & ESD Materials",
    prod_2: "Packing Materials & Cartons",
    prod_3: "Industrial O-Rings, Gaskets, & Seals",
    prod_4: "Wire Harnesses, Power Cords, & EV Chargers",
    prod_5: "Industrial & Lab Chemicals",
    prod_6: "Designed Screws & Connectors",
    prod_7: "Motor & Drive",
    prod_8: "Factory Safety Equipment",
    prod_group_industrial: "Industrial Solutions",
    prod_group_inhouse: "Inhouse Brands",
    inhouse_prod_1: "The White Ivory (Coming Soon)",
    catalogue_title: "Download Catalogue",
    catalogue_desc: "Scan the QR code or click the button below to view our full product catalogue.",
    catalogue_btn: "Download via Google Drive",
    contact_title: "Contact Us",
    contact_company: "OCTO NOTO CO., LTD.",
    contact_address: "88/206 Grande Pleno Suksawat-Rama 3, Pracha Uthit 54, Thung Khru District, Bangkok 10140, Thailand",
    footer_copy: "© 2026 OCTO NOTO CO., LTD. All Rights Reserved.",
    form_name_label: "Full Name",
    form_name_placeholder: "John Doe",
    form_company_label: "Company Name",
    form_company_placeholder: "Your Company Ltd.",
    form_email_label: "Email Address",
    form_email_placeholder: "john@example.com",
    form_phone_label: "Phone Number",
    form_phone_placeholder: "+1 234 567 8900",
    form_subject_label: "Subject",
    form_subject_placeholder: "Inquiry about VCI Packaging",
    form_message_label: "Message / Inquiry",
    form_message_placeholder: "Please describe the products or services you are looking for...",
    form_submit: "Send Message",
    form_submitting: "Sending...",
    form_success: "Thank you! Your message has been sent successfully. Our team will contact you shortly.",
    form_error: "Oops! Something went wrong. Please try again.",
    form_validation: "Please fill out all required fields.",
    open_maps: "Open in Google Maps",
    // VCI Product Page
    vci_page_title: "Anti-Rust & ESD Packaging",
    vci_title: "Industrial-Grade VCI Anti-Rust Packaging & ESD Solutions",
    vci_intro: "We are experts in anti-corrosion and anti-rust packaging for the industrial sector. We select premium imported raw materials and master rolls, offering made-to-order sizing and designs for the ultimate protection of your metal and electronic components.",
    vci_types_title: "Our Products & Services",
    vci_type1_title: "VCI Anti-Rust Packaging",
    vci_type1_p1: "VCI Bag: Plastic packaging infused with Volatile Corrosion Inhibitors to protect metal parts and machinery from rusting during storage and transport. Clean, safe, and leaves no oily residue.",
    vci_type1_p2: "VCI Paper: High-quality anti-rust wrapping paper, ideal for automotive parts, spare parts, and machine tools.",
    vci_type1_p3: "Custom Sizing: Made-to-order VCI bags and papers tailored to your exact specifications for a perfect fit, reducing packaging waste.",
    vci_type2_title: "Anti-Static Bag",
    vci_type2_desc: "Packaging designed to protect sensitive electronic components and circuit boards from electrostatic discharge, ensuring safety from origin to destination.",
    vci_type3_title: "Industrial Anti-Rust Oil",
    vci_type3_desc: "Premium anti-rust coating oil to protect metal surfaces from moisture and oxidation. Ideal for temporary storage during assembly or long-term preservation.",
    vci_why_title: "Why the Industrial Sector Trusts Us",
    vci_why1_title: "High-Quality Raw Materials",
    vci_why1_desc: "Using premium imported raw materials and master rolls, ensuring superior durability and protection.",
    vci_why2_title: "Customizable Services",
    vci_why2_desc: "Supporting custom-size manufacturing to perfectly match your actual usage requirements.",
    vci_why3_title: "Fast Delivery",
    vci_why3_desc: "Delivery within 2 weeks, ensuring your production line and logistics run continuously.",
    vci_cta_text: "Need a consultation on anti-rust packaging or want to order a custom size?",
    vci_cta_btn: "Contact Sales for Samples / Request a Quote",
    back_home: "Back to Home",
    // Packaging Product Page
    pkg_page_title: "Custom Cartons & Packaging",
    pkg_title: "Custom Printed Cartons and Die-Cut Boxes for Every Brand",
    pkg_intro: "Elevate your products and build brand trust with custom carton and die-cut box manufacturing. Support for logo printing (full color or single color black). We select high-quality, durable paper suitable for products, premium goods, and E-commerce parcels. No minimum order quantity.",
    pkg_features_title: "Features and Services",
    pkg_feat1_title: "Custom Size Cartons and Die-Cut Boxes",
    pkg_feat1_desc: "Designed and tailored to fit your products perfectly, saving cushioning material and creating a professional unboxing experience.",
    pkg_feat2_title: "Custom Logo Printing",
    pkg_feat2_p1: "Full Color: Ideal for brands seeking vibrant, realistic colors that match their Corporate Identity (CI).",
    pkg_feat2_p2: "Single Color / Black: Offers a classic, minimalist feel while effectively controlling production costs.",
    pkg_feat3_title: "Flexible Terms for Your Business",
    pkg_feat3_p1: "No Minimum Order: Perfect for SMEs testing the market or large brands doing limited runs.",
    pkg_feat3_p2: "Fast Production: Delivering quality work within 2 weeks after PO issuance and artwork confirmation.",
    pkg_why_title: "Why Choose Our Packaging Services?",
    pkg_why1_title: "Enhance Brand Image",
    pkg_why1_desc: "Logo-printed boxes add value, making your products look more premium and professional.",
    pkg_why2_title: "Cost-Effective & Exact Specs",
    pkg_why2_desc: "Produced to exact usage sizes, reducing storage space and transport damage.",
    pkg_why3_title: "Fast & Standardized Service",
    pkg_why3_desc: "Strict quality control at every step with on-time delivery.",
    pkg_cta_text: "Want to order custom logo-printed cartons?",
    pkg_cta_btn: "Contact us for consultation & pricing / Send artwork for a quote",
    // O-ring Product Page
    oring_page_title: "Industrial O-Rings, Gaskets & Seals",
    oring_title: "Premium Industrial O-Rings, Gaskets, & Seals for Hydraulics, Pneumatics, and Heavy Machinery",
    oring_intro: "Carefully selected high-quality rubber materials resistant to chemicals, heat, and high pressure, meeting the specific demands of the industrial sector.",
    oring_types_title: "Industrial Product Types",
    oring_type1_title: "O-Ring",
    oring_type1_desc: "Circular rubber gaskets for preventing liquid and gas leaks in machinery joints. Available in various material grades such as NBR, Viton, EPDM, and Silicone to suit specific temperatures and chemicals.",
    oring_type2_title: "Industrial Gasket",
    oring_type2_desc: "Sheet gaskets and custom-cut gaskets for pipe flanges, exhausts, tank covers, and machinery connections, preventing leaks under high pressure.",
    oring_type3_title: "Industrial Seal",
    oring_type3_desc: "Oil seals, hydraulic seals, and various leakage prevention seals that help extend machinery lifespan, reduce wear, and prevent contaminants from entering the system.",
    oring_why_title: "Our Features & Services",
    oring_why1_title: "Industry Standard Materials",
    oring_why1_desc: "Selecting materials resistant to wear, oil, chemicals, and extreme weather conditions.",
    oring_why2_title: "Sourcing & Custom Cutting",
    oring_why2_desc: "Sourcing standard size O-rings and gaskets (AS568, JIS) or cutting according to blueprints and customer samples.",
    oring_why3_title: "Fast Delivery",
    oring_why3_desc: "Supporting your maintenance and production lines to run smoothly without interruption.",
    oring_cta_text: "Looking for special spec O-rings, gaskets, or seals for your machinery?",
    oring_cta_btn: "Contact our Sales Engineering team to inquire about stock and special sizes"
  },
  th: {
    nav_home: "หน้าแรก",
    nav_about: "เกี่ยวกับเรา",
    nav_products: "สินค้าและบริการ",
    nav_contact: "ติดต่อเรา",
    hero_headline: "โซลูชันการจัดหาสินค้าและคู่ค้าเชิงยุทธศาสตร์ระดับโลก",
    hero_subhead: "บริการนำเข้า ส่งออก และจัดหาสินค้าอุตสาหกรรมภายในประเทศ เชื่อมต่อธุรกิจของคุณกับซัพพลายเชนคุณภาพสูงทั่วโลก",
    hero_cta: "ดูบริการของเรา",
    about_title: "เกี่ยวกับ ออคโต โนโตะ",
    about_desc: "บริษัทการค้าชั้นนำในประเทศไทย ที่มีความเชี่ยวชาญด้านการจัดหาเชิงเทคนิค การควบคุมคุณภาพ และการจัดการซัพพลายเชนระหว่างประเทศ เราทำหน้าที่เป็นพันธมิตรเชิงยุทธศาสตร์เพื่อให้มั่นใจว่าลูกค้าของเราได้รับสินค้าที่เหมาะสมที่สุดสำหรับการใช้งานเฉพาะด้าน",
    val_1_title: "การจัดหาเชิงเทคนิค",
    val_1_desc: "ให้คำปรึกษาเพื่อหาสินค้าที่ตรงความต้องการ",
    val_2_title: "คุณภาพต้องมาก่อน",
    val_2_desc: "ตรวจสอบผู้ผลิตและควบคุมคุณภาพอย่างเข้มงวด",
    val_3_title: "พันธมิตรเชิงยุทธศาสตร์",
    val_3_desc: "เน้นคุณค่าระยะยาว ความน่าเชื่อถือ และราคาที่โปร่งใส",
    prod_title: "สินค้าและบริการ",
    prod_1: "บรรจุภัณฑ์กันสนิมและอุปกรณ์ป้องกันไฟฟ้าสถิต",
    prod_2: "วัสดุบรรจุภัณฑ์ กล่องกระดาษ และฟิล์มยืด",
    prod_3: "โอริง ปะเก็น และซีลอุตสาหกรรม",
    prod_4: "ชุดสายไฟ สายไฟ และเครื่องชาร์จรถยนต์ไฟฟ้า",
    prod_5: "เคมีภัณฑ์สำหรับอุตสาหกรรมและห้องปฏิบัติการ",
    prod_6: "สกรูออกแบบพิเศษและข้อต่ออุตสาหกรรม",
    prod_7: "มอเตอร์และระบบขับเคลื่อน (Motor & Drive)",
    prod_8: "อุปกรณ์เซฟตี้ในโรงงาน (Factory Safety Equipment)",
    prod_group_industrial: "สินค้าอุตสาหกรรม",
    prod_group_inhouse: "แบรนด์ภายในองค์กร (Inhouse Brand)",
    inhouse_prod_1: "The White Ivory (เร็วๆ นี้)",
    catalogue_title: "ดาวน์โหลดแคตตาล็อก",
    catalogue_desc: "สแกนคิวอาร์โค้ดหรือคลิกปุ่มด้านล่างเพื่อดูแคตตาล็อกสินค้าทั้งหมดของเรา",
    catalogue_btn: "ดาวน์โหลดผ่าน Google Drive",
    contact_title: "ติดต่อเรา",
    contact_company: "บริษัท ออคโต โนโตะ จำกัด",
    contact_address: "88/206 หมู่บ้าน แกรนด์พลีโน สุขสวัสดิ์-พระราม3 ประชาอุทิศ 54 เขตทุ่งครุ กรุงเทพมหานคร 10140",
    footer_copy: "© 2026 OCTO NOTO CO., LTD. สงวนลิขสิทธิ์",
    form_name_label: "ชื่อ-นามสกุล",
    form_name_placeholder: "สมชาย ใจดี",
    form_company_label: "ชื่อบริษัท",
    form_company_placeholder: "บริษัท ของคุณ จำกัด",
    form_email_label: "อีเมล",
    form_email_placeholder: "somchai@example.com",
    form_phone_label: "เบอร์โทรศัพท์",
    form_phone_placeholder: "081-234-5678",
    form_subject_label: "หัวข้อติดต่อ",
    form_subject_placeholder: "สอบถามเรื่องบรรจุภัณฑ์กันสนิม",
    form_message_label: "ข้อความ / รายละเอียดสินค้าที่ต้องการให้จัดหา",
    form_message_placeholder: "โปรดระบุรายละเอียดสินค้า หรือบริการที่คุณกำลังมองหา...",
    form_submit: "ส่งข้อความ",
    form_submitting: "กำลังส่ง...",
    form_success: "ขอบคุณค่ะ! ระบบได้ส่งข้อมูลของท่านเรียบร้อยแล้ว เจ้าหน้าที่ของเราจะติดต่อกลับโดยเร็วที่สุด",
    form_error: "เกิดข้อผิดพลาดบางอย่าง กรุณาลองใหม่อีกครั้ง",
    form_validation: "กรุณากรอกข้อมูลในช่องที่กำหนดให้ครบถ้วน",
    open_maps: "เปิดบน Google Maps",
    // VCI Product Page
    vci_page_title: "บรรจุภัณฑ์กันสนิมและอุปกรณ์ป้องกันไฟฟ้าสถิต",
    vci_title: "โซลูชันบรรจุภัณฑ์กันสนิม ถุง VCI และวัสดุป้องกันไฟฟ้าสถิตมาตรฐานอุตสาหกรรม",
    vci_intro: "เราคือผู้เชี่ยวชาญด้านบรรจุภัณฑ์ป้องกันการกัดกร่อนและสนิมสำหรับภาคอุตสาหกรรม คัดสรรวัตถุดิบและ Master Roll เกรดพรีเมียมนำเข้าจากต่างประเทศ พร้อมให้บริการตัดแต่งตามขนาดและรูปแบบที่ลูกค้าต้องการ (Made-to-Order) เพื่อการปกป้องชิ้นส่วนโลหะและอิเล็กทรอนิกส์อย่างมีประสิทธิภาพสูงสุด",
    vci_types_title: "ประเภทผลิตภัณฑ์และบริการของเรา",
    vci_type1_title: "บรรจุภัณฑ์ป้องกันสนิมเทคโนโลยี VCI (VCI Anti-Rust Packaging)",
    vci_type1_p1: "ถุงกันสนิม (VCI Bag): ถุงพลาสติกบรรจุภัณฑ์ผสมสารระเหยยับยั้งสนิม (Volatile Corrosion Inhibitor) ช่วยปกป้องชิ้นส่วนโลหะและเครื่องจักรไม่ให้เกิดสนิมระหว่างการจัดเก็บและการขนส่ง สะอาด ปลอดภัย ไม่ทิ้งคราบมันบนพื้นผิวชิ้นงาน",
    vci_type1_p2: "กระดาษกันสนิม (VCI Paper): กระดาษห่อกันสนิมคุณภาพสูง เหมาะสำหรับการห่อหุ้มชิ้นส่วนยานยนต์ อะไหล่ และเครื่องมือกล",
    vci_type1_p3: "บริการตัดตามขนาด: รับผลิตและตัดถุงกันสนิม กระดาษกันสนิม ตามขนาดและสเปกเฉพาะของลูกค้า เพื่อให้ใช้งานได้พอดีกับชิ้นงาน ลดขยะบรรจุภัณฑ์",
    vci_type2_title: "ถุงกันไฟฟ้าสถิต (Anti-Static Bag)",
    vci_type2_desc: "บรรจุภัณฑ์ป้องกันความเสียหายจากประจุไฟฟ้าสถิตสำหรับอุตสาหกรรมอิเล็กทรอนิกส์ แผงวงจร และอุปกรณ์ที่มีความอ่อนไหว ป้องกันความเสียหายตั้งแต่ต้นทางจนถึงมือผู้รับ",
    vci_type3_title: "น้ำมันกันสนิมอุตสาหกรรม (Anti-Rust Oil)",
    vci_type3_desc: "น้ำมันเคลือบป้องกันสนิมคุณภาพเยี่ยม ช่วยเคลือบผิวโลหะเพื่อป้องกันความชื้นและการเกิดออกซิเดชัน เหมาะสำหรับงานพักผิวชิ้นงานระหว่างรอประกอบหรือเก็บรักษาในระยะยาว",
    vci_why_title: "จุดเด่นที่เราได้รับความไว้วางใจจากภาคอุตสาหกรรม",
    vci_why1_title: "Raw Material คุณภาพสูง",
    vci_why1_desc: "ใช้วัตถุดิบและ Master Roll นำเข้าจากต่างประเทศ มั่นใจได้ในมาตรฐานความทนทานและการปกป้อง",
    vci_why2_title: "บริการตัดแต่งตามความต้องการ",
    vci_why2_desc: "รองรับการผลิตตามขนาด (Custom Size) ที่ลูกค้าต้องการใช้งานจริง",
    vci_why3_title: "ส่งมอบรวดเร็ว",
    vci_why3_desc: "บริการจัดส่งสินค้าถึงมือลูกค้าภายใน 2 สัปดาห์ ช่วยให้สายการผลิตและการขนส่งของคุณดำเนินไปได้อย่างต่อเนื่อง",
    vci_cta_text: "ต้องการปรึกษาเรื่องบรรจุภัณฑ์กันสนิม หรือสั่งตัดตามขนาดพิเศษ?",
    vci_cta_btn: "ติดต่อทีมงานฝ่ายขายเพื่อขอตัวอย่างสินค้า / ขอใบเสนอราคา",
    back_home: "กลับสู่หน้าหลัก",
    // Packaging Product Page
    pkg_page_title: "กล่องกระดาษและกล่องไดคัทพิมพ์ลายตามสั่ง",
    pkg_title: "กล่องกระดาษและกล่องไดคัทพิมพ์ลายตามสั่ง ตอบโจทย์ทุกบรรจุภัณฑ์แบรนด์คุณ",
    pkg_intro: "ยกระดับสินค้าและสร้างความน่าเชื่อถือให้กับแบรนด์ด้วยบริการผลิต กล่องกระดาษ และ กล่องไดคัท ตามขนาดและดีไซน์เฉพาะตัว รองรับการพิมพ์โลโก้หรือลวดลายตามความต้องการ (พิมพ์สีคมชัด หรือพิมพ์ดำสีเดียว) คัดสรรวัสดุกระดาษคุณภาพดี แข็งแรงทนทาน เหมาะสำหรับใส่สินค้า ผลิตภัณฑ์พรีเมียม และกล่องพัสดุ E-commerce พร้อมให้บริการด้วยความใส่ใจ ไม่มีขั้นต่ำในการสั่งผลิต",
    pkg_features_title: "ลักษณะเด่นและบริการของเรา",
    pkg_feat1_title: "กล่องไดคัทและกล่องกระดาษสั่งทำตามขนาด (Custom Size)",
    pkg_feat1_desc: "ออกแบบและตัดเย็บรูปทรงกล่องให้พอดีกับสินค้าของคุณ ช่วยประหยัดวัสดุกันกระแทก ดูเป็นมืออาชีพ และสร้างความประทับใจแรกพบเมื่อลูกค้าเปิดกล่อง (Unboxing Experience)",
    pkg_feat2_title: "บริการพิมพ์โลโก้และลวดลายแบรนด์คุณ (Logo Printing)",
    pkg_feat2_p1: "พิมพ์สีคมชัด: เหมาะสำหรับแบรนด์ที่ต้องการความโดดเด่น สีสันสวยงาม สมจริง ตรงตามCorporate Identity (CI)",
    pkg_feat2_p2: "พิมพ์ดำสีเดียว (Single Color / Black): ให้ความรู้สึกเรียบหรู คลาสสิก มินิมอล และช่วยควบคุมต้นทุนการผลิตได้อย่างมีประสิทธิภาพ",
    pkg_feat3_title: "ยืดหยุ่นด้วยเงื่อนไขที่ตอบโจทย์ธุรกิจ",
    pkg_feat3_p1: "ไม่มีขั้นต่ำ (No Minimum Order): รองรับทั้งธุรกิจขนาดเล็ก (SMEs) ที่ต้องการทดลองตลาด หรือแบรนด์ใหญ่ที่ต้องการผลิตจำนวนจำกัด",
    pkg_feat3_p2: "ระยะเวลาการผลิตที่รวดเร็ว: พร้อมส่งมอบงานคุณภาพภายใน 2 สัปดาห์ หลังจากที่ลูกค้าเปิดคำสั่งซื้อ (PO) และยืนยันความถูกต้องของแบบพิมพ์ (Artwork) เป็นที่เรียบร้อยแล้ว",
    pkg_why_title: "ทำไมต้องเลือกใช้บริการกล่องบรรจุภัณฑ์ของเรา?",
    pkg_why1_title: "เสริมภาพลักษณ์แบรนด์",
    pkg_why1_desc: "กล่องพิมพ์โลโก้ช่วยเพิ่มมูลค่าให้สินค้าดูพรีเมียมและเป็นมืออาชีพยิ่งขึ้น",
    pkg_why2_title: "คุ้มค่า ตรงสเปก",
    pkg_why2_desc: "ผลิตตามขนาดที่ใช้งานจริง ลดพื้นที่จัดเก็บและลดความเสียหายระหว่างขนส่ง",
    pkg_why3_title: "บริการรวดเร็วและได้มาตรฐาน",
    pkg_why3_desc: "ควบคุมคุณภาพการผลิตทุกขั้นตอน พร้อมจัดส่งตรงเวลา",
    pkg_cta_text: "ต้องการสั่งผลิตกล่องกระดาษพิมพ์โลโก้ตามขนาดของคุณ?",
    pkg_cta_btn: "ติดต่อทีมงานเพื่อปรึกษาขนาดและประเมินราคา / ส่งแบบพิมพ์เพื่อขอใบเสนอราคา",
    // O-ring Product Page
    oring_page_title: "โอริง ปะเก็น และซีลอุตสาหกรรม",
    oring_title: "โอริง ปะเก็น และซีลอุตสาหกรรมเกรดพรีเมียม ตอบโจทย์ทุกการใช้งานในระบบไฮดรอลิก นิวเมติกส์ และเครื่องจักรกลหนัก",
    oring_intro: "คัดสรรวัสดุยางคุณภาพสูงทนทานต่อสารเคมี ความร้อน และแรงดันสูง รองรับความต้องการเฉพาะของภาคอุตสาหกรรม",
    oring_types_title: "ประเภทผลิตภัณฑ์อุตสาหกรรม",
    oring_type1_title: "โอริง (O-Ring)",
    oring_type1_desc: "ปะเก็นยางวงกลมสำหรับป้องกันการรั่วไหลของของเหลวและก๊าซในข้อต่อเครื่องจักร มีหลากหลายเกรดวัสดุ เช่น NBR, Viton, EPDM และ Silicone เพื่อให้เหมาะสมกับอุณหภูมิและสารเคมีเฉพาะงาน",
    oring_type2_title: "ปะเก็นอุตสาหกรรม (Gasket)",
    oring_type2_desc: "ปะเก็นแผ่นและปะเก็นตัดตามแบบ สำหรับหน้าแปลนท่อ ท่อไอเสีย ฝาครอบถัง และจุดเชื่อมต่อเครื่องจักร ป้องกันการรั่วซึมภายใต้แรงดันสูง",
    oring_type3_title: "ซีลอุตสาหกรรม (Industrial Seal)",
    oring_type3_desc: "ซีลน้ำมัน ซีลไฮดรอลิก และซีลกันรั่วประเภทต่างๆ ช่วยยืดอายุการใช้งานของเครื่องจักร ลดการสึกหรอ และป้องกันสิ่งแปลกปลอมเข้าสู่ระบบ",
    oring_why_title: "จุดเด่นและบริการของเรา",
    oring_why1_title: "วัสดุมาตรฐานอุตสาหกรรม",
    oring_why1_desc: "เลือกใช้วัสดุที่ทนทานต่อการสึกหรอ น้ำมัน สารเคมี และสภาพอากาศที่รุนแรง",
    oring_why2_title: "บริการจัดหาและตัดตามสเปก",
    oring_why2_desc: "รองรับการจัดหาโอริงและปะเก็นตามขนาดมาตรฐาน (AS568, JIS) หรือตัดตามแบบพิมพ์เขียวและตัวอย่างของลูกค้า",
    oring_why3_title: "บริการจัดส่งรวดเร็ว",
    oring_why3_desc: "สนับสนุนการซ่อมบำรุงและสายการผลิตของคุณให้ดำเนินต่อไปได้อย่างไม่สะดุด",
    oring_cta_text: "กำลังมองหาโอริง ปะเก็น หรือซีลสเปกพิเศษสำหรับเครื่องจักรของคุณอยู่ใช่ไหม?",
    oring_cta_btn: "ติดต่อทีมงานวิศวกรฝ่ายขายเพื่อสอบถามสต็อกสินค้าและขนาดพิเศษ"
  }
};
